using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PascalCompiler.StatementParser
{
    public enum TErrorCode
    {
        None,
        Unrecognizable,
        TooMany,
        UnexpectedEndOfFile,
        InvalidNumber,
        InvalidFraction,
        InvalidExponent,
        TooManyDigits,
        RealOutOfRange,
        IntegerOutOfRange,
        MissingRightParen,
        InvalidExpression,
        InvalidAssignment,
        MissingIdentifier,
        MissingColonEqual,
        UndefinedIdentifier,
        StackOverflow,
        InvalidStatement,
        UnexpectedToken,
        MissingSemicolon,
        MissingComma,
        MissingDO,
        MissingUNTIL,
        MissingTHEN,
        InvalidFORControl,
        MissingOF,
        InvalidConstant,
        MissingConstant,
        MissingColon,
        MissingEND,
        MissingTOorDOWNTO,
        RedefinedIdentifier,
        MissingEqual,
        InvalidType,
        NotATypeIdentifier,
        InvalidSubrangeType,
        NotAConstantIdentifier,
        MissingDotDot,
        IncompatibleTypes,
        InvalidTarget,
        InvalidIdentifierUsage,
        IncompatibleAssignment,
        MinGtMax,
        MissingLeftBracket,
        MissingRightBracket,
        InvalidIndexType,
        MissingBEGIN,
        MissingPeriod,
        TooManySubscripts,
        InvalidField,
        NestingTooDeep,
        MissingPROGRAM,
        AlreadyForwarded,
        WrongNumberOfParms,
        InvalidVarParm,
        NotARecordVariable,
        MissingVariable,
        CodeSegmentOverflow,
        UnimplementedFeature,
    }

}
